-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 12:35:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Bravo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bravo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bravo` DEFAULT CHARACTER SET latin1 ;
USE `Bravo` ;

-- -----------------------------------------------------
-- Table `Bravo`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bravo`.`fornecedor` (
  `idFornecedor` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeFornecedor` VARCHAR(45) NOT NULL,
  `cnpjFornecedor` VARCHAR(45) NOT NULL,
  `contatoFornecedor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `cnpjFornecedor_UNIQUE` (`cnpjFornecedor` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
